#include <atomic>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <tuple>
#include <utility>

#include <ESPressio_Event.hpp>
#include <ESPressio_Platform_FreeRTOS.hpp>
#include <memory/MemoryResourceProvider.hpp>
#include <synchronization/SpinLockProvider.hpp>
namespace Demo {
namespace Event=ESPressio::Event; namespace Memory=ESPressio::Memory; namespace Primitives=ESPressio::Primitives; namespace Threading=ESPressio::Threading; namespace CF=ESPressio::System::CompositionFramework;
using SignalProvider=ESPressio::Platform::FreeRTOS::Synchronization::SignalProvider; using ExecutionContextProvider=ESPressio::Platform::FreeRTOS::Execution::ExecutionContextProvider; using SpinLockProvider=ESPressio::Platform::ESPIDF::Synchronization::SpinLockProvider; using MutexProvider=ESPressio::Platform::FreeRTOS::Synchronization::MutexProvider; using MemoryResourceProvider=ESPressio::Platform::Portable::Memory::MemoryResourceProvider;
struct ListenerThread final {};
struct BoundaryEvent final { inline static constexpr ESPressio::System::TypeIdentifier Identifier{ESPressio::System::TypeIdentifier::Storage{0x45,0x44,0x50,0,0,0,0,3}}; using Family=Event::Family; std::int32_t Value{}; };
}
namespace ESPressio::Bounded { template<> struct MemoryBoundedTraits<Demo::BoundaryEvent>:MemoryBoundedValueDeclaration<false,std::int32_t>{}; }
namespace Demo {
using PrimitiveTopology=Primitives::Topology<Event::Deploy<BoundaryEvent,2U,Event::Queue<2U>,Event::UntilHandoffOnly>,Event::Observe<ListenerThread,BoundaryEvent>>; using EventPlan=Event::PlanFor<PrimitiveTopology>; using PoolSpec=Event::OccurrencePoolSpec<EventPlan,BoundaryEvent>;
using MemoryTopology=Memory::MemoryTopology<MemoryResourceProvider,Memory::SharedReserve<0U,MemoryResourceProvider>,PoolSpec>; using MemoryComposition=Memory::MemoryComposition<MemoryResourceProvider>; using Allocator=typename MemoryComposition::template Select<Memory::SharedReserveAllocationRequirement,CF::SelectUnique>; using MemoryRuntime=Memory::MemoryRuntime<MemoryTopology,MemoryComposition,MutexProvider,SignalProvider>;
using ThreadingTopology=Threading::ThreadingTopology<Threading::DedicatedThread<ListenerThread,Threading::StackCapacity<4096U>>>;
struct Control{using DrainFn=Event::DrainResult(*)(void*,std::size_t) noexcept;void* Runtime{};DrainFn Drain{};}; struct Loop{Control* C{};void operator()(Threading::ThreadContext& ctx) noexcept{while(!ctx.IsStopRequested()){if(C&&C->Runtime&&C->Drain){auto d=C->Drain(C->Runtime,8U);if(d.WorkRemaining)continue;}if(ctx.Wait()!=Threading::ThreadWaitResult::Woken)return;}}};
struct Handler final:CF::Provider<Event::Composition::Domain,CF::Offers<CF::Offer<Event::Composition::ListenerCallback<ListenerThread,BoundaryEvent>>>>{std::atomic<std::int32_t> Last{0};std::atomic<unsigned> Count{0};void OnEvent(const BoundaryEvent& e) noexcept{Last.store(e.Value,std::memory_order_relaxed);Count.fetch_add(1,std::memory_order_release);}};
using EventMutex=Threading::OrdinaryMutexProvider<Event::Composition::RuntimeMutexIdentity,MutexProvider>; using EventComposition=CF::Composition<Event::Composition::Domain,Handler>; using ThreadingComposition=CF::Composition<Threading::Domain,ThreadingTopology,EventMutex>; using Architecture=CF::Architecture<EventComposition,ThreadingComposition>;
template<class R>Event::DrainResult Drain(void* p,std::size_t n) noexcept{return static_cast<R*>(p)->template Drain<ListenerThread>(n);} enum class TransportResult:std::uint8_t{Accepted}; struct FakeTransport{std::atomic<unsigned> Calls{0};std::atomic<std::int32_t> Last{0};TransportResult operator()(const BoundaryEvent& e) noexcept{Last.store(e.Value,std::memory_order_relaxed);Calls.fetch_add(1,std::memory_order_relaxed);return TransportResult::Accepted;}};
int Run(){MemoryResourceProvider resource;MutexProvider mm;Allocator alloc;MemoryRuntime memory(mm,alloc,resource);Memory::MemoryTopologyInitializationFailure mf{};if(memory.Initialize(mf)!=Memory::MemoryTopologyInitializationResult::Succeeded)return 1;Control control{};auto bindings=std::make_tuple(Threading::BindDedicatedThread<ListenerThread>(Loop{&control}));using Bindings=decltype(bindings);using TR=Threading::StaticThreadingRuntime<ThreadingTopology,Bindings,SignalProvider,ExecutionContextProvider,SpinLockProvider,MutexProvider>;static TR threading(std::move(bindings));if(threading.Initialize()!=Threading::ThreadingInitializationResult::Succeeded||threading.Start()!=Threading::ThreadingStartResult::Succeeded)return 2;EventMutex em;Handler handler;using EB=Event::Bootstrap<Architecture,EventPlan,MemoryRuntime,TR>;EB bootstrap(memory,threading,em,handler);if(bootstrap.Initialize()!=Event::InitializationResult::Initialized)return 3;auto& events=bootstrap.RuntimeInstance();using ER=std::remove_reference_t<decltype(events)>;control.Runtime=&events;control.Drain=&Drain<ER>;if(events.Subscribe<ListenerThread,BoundaryEvent>()!=Event::SubscribeResult::Subscribed)return 4;auto listener=threading.ThreadHandle<ListenerThread>();if(listener.Start()!=Threading::ThreadStartResult::Started)return 5;FakeTransport transport;BoundaryEvent event{77};auto both=events.Dispatch(Event::LocalAndRemote{},event,Event::UntilHandoff{},transport);if(both.Local()!=Event::DispatchResult::Accepted||!both.Remote().WasAttempted()||both.Remote().Result()!=TransportResult::Accepted||transport.Calls.load()!=1||transport.Last.load()!=77)return 6;for(std::size_t i=0;i<200000U&&handler.Count.load(std::memory_order_acquire)==0U;++i)ExecutionContextProvider::Yield();if(handler.Count.load()!=1||handler.Last.load()!=77)return 7;auto remoteOnly=Event::DispatchScoped(Event::RemoteOnly{},BoundaryEvent{88},Event::UntilHandoff{},transport);if(!remoteOnly.WasAttempted()||transport.Calls.load()!=2||transport.Last.load()!=88)return 8;if(events.Ingress(BoundaryEvent{99})!=Event::DispatchResult::Accepted)return 9;for(std::size_t i=0;i<200000U&&handler.Count.load(std::memory_order_acquire)<2U;++i)ExecutionContextProvider::Yield();if(handler.Count.load()!=2||handler.Last.load()!=99)return 10;if(listener.RequestStop()!=Threading::ThreadStopRequestResult::Accepted)return 11;while(listener.State()==Threading::ThreadState::Running)ExecutionContextProvider::Yield();if(threading.BeginShutdown()!=Threading::ThreadingShutdownResult::Accepted)return 12;while(!threading.IsExecutionQuiescent())ExecutionContextProvider::Yield();if(threading.FinalizeShutdown()!=Threading::ThreadingFinalizationResult::Completed)return 13;if(memory.TearDown()!=Memory::MemoryTopologyTeardownResult::Succeeded)return 14;std::printf("EDP-Event transport-boundary: PASS\n");return 0;}
}
#ifdef ARDUINO
void setup(){static_cast<void>(Demo::Run());}void loop(){}
#else
extern "C" void app_main(){static_cast<void>(Demo::Run());}
#endif
